/* WAYPOINT pricing governance register · v2.1 · generated 2026-07-19
   Source of truth: "AIR, SEA, STAY RATES .xlsx" (uploaded 2026-07-19). Figures verified against workbook cells.
   confirmedBy/confirmedDate/validFrom/reviewDate: null — Commercial approval metadata pending. */
export type PricingRecord = {
  assetId: string; assetName: string; category: "air" | "sea" | "stay";
  sourceWorkbook: string; sourceSheet: string; sourceRow: number;
  publicPriceFrom: number | null; currency: string; publicPriceUnit: string; publicPriceLabel: string;
  shortQualifier: string; fullQualifier: string; minimumTerm: string | null;
  includedSummary: string | null; excludedSummary: string | null;
  confirmedBy: string | null; confirmedDate: string | null; validFrom: string | null; reviewDate: string | null;
  sourceReference: string; priceConfirmed: boolean; priceOnApplication: boolean;
  pricingVisibility: "public"; seasonalOperation: boolean; internalNotes: string;
};

export const PRICING_REGISTER: PricingRecord[] = [
  { assetId: "citation-cj4", assetName: "Citation CJ4", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 2,
    publicPriceFrom: 5500, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $5,500 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 2", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "ec130", assetName: "EC130", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 3,
    publicPriceFrom: 4000, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $4,000 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 3", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "king-air-b200", assetName: "King Air B200", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 4,
    publicPriceFrom: 3500, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $3,500 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 4", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "pilatus-pc-12", assetName: "Pilatus PC-12", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 5,
    publicPriceFrom: 4000, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $4,000 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 5", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "challenger-605", assetName: "Bombardier Challenger 605", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 6,
    publicPriceFrom: 9900, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $9,900 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 6", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "gulfstream-g650", assetName: "Gulfstream G650", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 7,
    publicPriceFrom: 15500, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $15,500 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 7", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "robinson-r44", assetName: "Robinson R44", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 8,
    publicPriceFrom: 2500, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $2,500 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 8", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "robinson-r66", assetName: "Robinson R66", category: "air", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "AIR", sourceRow: 9,
    publicPriceFrom: 3000, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $3,000 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on routing, positioning, airport charges, crew requirements and aircraft availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "AIR!row 9", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "alani", assetName: "M/Y ALANI", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 2,
    publicPriceFrom: 1800, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $1,800 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 2", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "rascal", assetName: "M/Y RASCAL", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 3,
    publicPriceFrom: 2500, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $2,500 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 3", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: true,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "nisi", assetName: "M/Y NISI", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 4,
    publicPriceFrom: 1700, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $1,700 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 4", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "capelli-stradivari-52", assetName: "Capelli Stradivari 52", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 5,
    publicPriceFrom: 1200, currency: "AUD", publicPriceUnit: "per hour", publicPriceLabel: "From AUD $1,200 per hour",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 5", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: true,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "aix", assetName: "M/Y AIX", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 6,
    publicPriceFrom: null, currency: "AUD", publicPriceUnit: "POA", publicPriceLabel: "Price on application",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 6", priceConfirmed: false, priceOnApplication: true, pricingVisibility: "public", seasonalOperation: true,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "aura", assetName: "M/Y AURA", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 7,
    publicPriceFrom: null, currency: "AUD", publicPriceUnit: "POA", publicPriceLabel: "Price on application",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 7", priceConfirmed: false, priceOnApplication: true, pricingVisibility: "public", seasonalOperation: true,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "impulsive", assetName: "M/Y IMPULSIVE", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 8,
    publicPriceFrom: null, currency: "AUD", publicPriceUnit: "POA", publicPriceLabel: "Price on application",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 8", priceConfirmed: false, priceOnApplication: true, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "murcielago", assetName: "M/Y MURCIELAGO", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 9,
    publicPriceFrom: null, currency: "AUD", publicPriceUnit: "POA", publicPriceLabel: "Price on application",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 9", priceConfirmed: false, priceOnApplication: true, pricingVisibility: "public", seasonalOperation: true,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "oneworld", assetName: "M/Y ONEWORLD", category: "sea", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "SEA", sourceRow: 10,
    publicPriceFrom: null, currency: "AUD", publicPriceUnit: "POA", publicPriceLabel: "Price on application",
    shortQualifier: "Indicative", fullQualifier: "Indicative charter rate. Final pricing depends on duration, cruising area, catering, beverages, guest requirements and availability.", minimumTerm: null,
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "SEA!row 10", priceConfirmed: false, priceOnApplication: true, pricingVisibility: "public", seasonalOperation: true,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "hti-residence", assetName: "HTI Residence", category: "stay", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "STAY", sourceRow: 2,
    publicPriceFrom: 4500, currency: "AUD", publicPriceUnit: "per night", publicPriceLabel: "From AUD $4,500 per night",
    shortQualifier: "Indicative", fullQualifier: "Indicative accommodation rate. Minimum stay, season, guest count, service requirements and availability may affect the final proposal.", minimumTerm: "3 nights",
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "STAY!row 2", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "noosa-residence", assetName: "NOOSA Residence", category: "stay", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "STAY", sourceRow: 3,
    publicPriceFrom: 9500, currency: "AUD", publicPriceUnit: "per night", publicPriceLabel: "From AUD $9,500 per night",
    shortQualifier: "Indicative", fullQualifier: "Indicative accommodation rate. Minimum stay, season, guest count, service requirements and availability may affect the final proposal.", minimumTerm: "3 nights",
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "STAY!row 3", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "syd-residence", assetName: "SYD Residence", category: "stay", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "STAY", sourceRow: 4,
    publicPriceFrom: 5000, currency: "AUD", publicPriceUnit: "per night", publicPriceLabel: "From AUD $5,000 per night",
    shortQualifier: "Indicative", fullQualifier: "Indicative accommodation rate. Minimum stay, season, guest count, service requirements and availability may affect the final proposal.", minimumTerm: "3 nights",
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "STAY!row 4", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "tasmania-lodge", assetName: "TASMANIA LODGE", category: "stay", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "STAY", sourceRow: 5,
    publicPriceFrom: 2500, currency: "AUD", publicPriceUnit: "per night", publicPriceLabel: "From AUD $2,500 per night",
    shortQualifier: "Indicative", fullQualifier: "Indicative accommodation rate. Minimum stay, season, guest count, service requirements and availability may affect the final proposal.", minimumTerm: "3 nights",
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "STAY!row 5", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
  { assetId: "tasmania-golf", assetName: "TASMANIA GOLF", category: "stay", sourceWorkbook: "AIR, SEA, STAY RATES .xlsx", sourceSheet: "STAY", sourceRow: 6,
    publicPriceFrom: 4500, currency: "AUD", publicPriceUnit: "per night", publicPriceLabel: "From AUD $4,500 per night",
    shortQualifier: "Indicative", fullQualifier: "Indicative accommodation rate. Minimum stay, season, guest count, service requirements and availability may affect the final proposal.", minimumTerm: "3 nights",
    includedSummary: null, excludedSummary: null, confirmedBy: null, confirmedDate: null, validFrom: null, reviewDate: null,
    sourceReference: "STAY!row 6", priceConfirmed: true, priceOnApplication: false, pricingVisibility: "public", seasonalOperation: false,
    internalNotes: "Commercial approval metadata pending. Imported 2026-07-19." },
];